### ISSUE TITLE
Newly scaffolded project throws node warnings 

### ISSUE THREAD

**Issue by candleshine** [sakuraapi/cli#3]
`npm WARN deprecated email-templates@2.7.1: 📫  Please upgrade to v3.1.5 (v3.0.x had a core bug with attachments and v3.1.5 now supports Node v6.4.0+). Also read the breaking changes for upgrading from v2 to v3 at https://github.com/niftylettuce/email-templates#v3-breaking-changes 📫
`
Testing implications of upgrading versions.

**Comment by candleshine** [comment]
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

**Comment by candleshine** [comment]
@etsuo says to yank email-templates.  will see if there are other unneeded dependencies in our scaffolding

**Comment by etsuo** [comment]
@candleshine I'm assuming this is closed with the merge of your PR - let me know if that's not the case.

**Comment by candleshine** [comment]
I agree with the closure
