### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [sakuraapi/cli#7]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by etsuo** [comment]
@Drulac, this is the first time I've gotten a direct solicitation to use a library by its author. lol - I'll have a look at what you've done when I get a chance next week.

I think long-term the right solution is to let the user choose which templating library he wants to use (I'm assuming you're talking about the template library being used for the email templates that are outputted, not the template engine that's being used internally. If it's the internal one, that's not going to change... it would make no noticeable difference to the cli user). 

Thanks for the input!

**Comment by Drulac** [comment]
Yes, it may be a good idea to let the user to have the choice ☺
